### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by morganwalker** [sighupio/gatekeeper-policy-manager#63]
Thank you for developing this UI. We were struggling to put some observability around Gatekeeper and this is what we needed.

I was wondering if there were plans to support pagination. On the "Constraints" tab, I can only see the first 20 violations of my policy. If I have more, there's no way to see past the first 20. It would be nice if I could either:
- choose how many violations to list, e.g. 10, 20, 50, 100, All
- choose "Next page" at the bottom of the list of 20
- infinity scrolling

Whatever is easiest but we need to be able to see all the violations.

**Comment by ralgozino** [comment]
Hi @morganwalker! Thanks for reaching out, I'm glad you are finding GPM useful :)

The 20 violations limit is not intended. Will look into this asap.

**Comment by ralgozino** [comment]
It turns out that is a Gatekeeper configuration issue. If you look at the constraint status field it also shows only 20 violations:

> Audit violations per constraint: set --constraint-violations-limit=123 (defaults to 20)

See the gatekeeper's readme for reference: https://github.com/open-policy-agent/gatekeeper

If you set the flag to a bigger number GPM will show more violations.

I'll add a warning to the view when violations > what GPM can show as a heads up to the user

**Comment by morganwalker** [comment]
Yup, you're exactly right. I increased my limit from 20 to 60 and they're all showing up. Thank you!

**Comment by ralgozino** [comment]
I've added this warning to GPM:
![image](https://user-images.githubusercontent.com/6362698/98384357-f3377280-204d-11eb-9fb8-fc1ae3331c97.png)

Thanks again for the report @morganwalker and please let us know if you find any other issue or you have any suggestion 😃
